version: "3.8"
services:
  db:
    image: postgres:16
    container_name: db_app
    env_file:
      - .env-non-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - "9999:8000"
    depends_on:
      - db
volumes:
  postgres_data: